import { useEffect, useRef, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, Divider, IconButton, Paper, Stack, TextField, Typography } from "@mui/material";
import { CancelOutlined, CheckCircleRounded, HearingRounded, KeyboardRounded, MicRounded, SendRounded, StopCircleRounded, TranslateRounded, VolumeUpRounded } from "@mui/icons-material";
import { api } from "../api/client";

interface Proposal { id: number; action_type: string; risk: string; status: string; summary: string; fields: Record<string, unknown>; expires_at: string }
interface Message { role: "user" | "assistant"; content: string; action?: Proposal }
interface MemoryMessage { role: "user" | "assistant"; content: string }
const prompts = ["There has been no water near my house since morning", "Pay my maintenance fee for this month", "Show my recent complaints", "What are the latest notices?"];

function recordingFormat() {
  const formats = [
    { mimeType: "audio/webm;codecs=opus", extension: "webm" },
    { mimeType: "audio/webm", extension: "webm" },
    { mimeType: "audio/mp4", extension: "m4a" },
    { mimeType: "audio/ogg;codecs=opus", extension: "ogg" },
  ];
  return formats.find(({ mimeType }) => MediaRecorder.isTypeSupported(mimeType));
}

export default function AI() {
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "Namaste. Speak in Hindi or Marathi, or type your request. I will check the right records and ask before making changes." }]);
  const [input, setInput] = useState(""); const [busy, setBusy] = useState(false); const [recording, setRecording] = useState(false); const [seconds, setSeconds] = useState(0);
  const [language, setLanguage] = useState("hi-IN"); const [voiceError, setVoiceError] = useState<string | null>(null);
  const [memoryMessages, setMemoryMessages] = useState<MemoryMessage[]>([]); const [conversationSummary, setConversationSummary] = useState(""); const [speakingText, setSpeakingText] = useState<string | null>(null);
  const endRef = useRef<HTMLDivElement>(null); const recorderRef = useRef<MediaRecorder | null>(null); const streamRef = useRef<MediaStream | null>(null); const chunksRef = useRef<Blob[]>([]); const timerRef = useRef<number | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null); const audioContextRef = useRef<AudioContext | null>(null); const animationRef = useRef<number | null>(null);
  useEffect(() => {
  endRef.current?.scrollIntoView({ behavior: "smooth" });
}, [messages, busy]);

useEffect(() => {
  return () => {
    streamRef.current?.getTracks().forEach((track) => {
      track.stop();
    });

    if (timerRef.current !== null) {
      window.clearInterval(timerRef.current);
    }
    window.speechSynthesis?.cancel();
    if (animationRef.current !== null) cancelAnimationFrame(animationRef.current);
    void audioContextRef.current?.close();
  };
}, []);

  function stopSpeaking() { window.speechSynthesis?.cancel(); setSpeakingText(null); }
  function speak(text: string) { if (!("speechSynthesis" in window)) { setVoiceError("Read aloud is unavailable in this browser."); return; } stopSpeaking(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = language; utterance.onstart = () => setSpeakingText(text); utterance.onend = () => setSpeakingText(null); utterance.onerror = () => setSpeakingText(null); window.speechSynthesis.speak(utterance); }
  function appendResult(data: any, translated?: string) { setMemoryMessages(data.memory_messages || []); setConversationSummary(data.conversation_summary || ""); if (translated) setMessages((m) => [...m, { role: "user", content: `Translated to English: ${translated}` }, { role: "assistant", content: data.reply, action: data.action }]); else setMessages((m) => [...m, { role: "assistant", content: data.reply, action: data.action }]); speak(data.reply); }
  async function send(text = input) { if (!text.trim() || busy) return; stopSpeaking(); setMessages((m) => [...m, { role: "user", content: text.trim() }]); setInput(""); setBusy(true); try { const { data } = await api.post("/ai/chat", { message: text.trim(), language, history: memoryMessages, conversation_summary: conversationSummary || null }); appendResult(data); } catch (e: any) { setMessages((m) => [...m, { role: "assistant", content: e?.response?.data?.detail || "The AI service could not be reached. Manual services still work." }]); } finally { setBusy(false); } }
  async function sendVoice(blob: Blob, extension: string) { setBusy(true); try { const form = new FormData(); form.append("audio", blob, `panchayat-request.${extension}`); form.append("language", language); form.append("history", JSON.stringify(memoryMessages)); form.append("conversation_summary", conversationSummary); const { data } = await api.post("/ai/voice", form, { timeout: 45_000 }); appendResult(data, data.input_transcript); } catch (e: any) { setVoiceError(e?.response?.data?.detail || "The recording could not be translated. Please retry or type your request."); } finally { setBusy(false); } }
  function startWaveform(stream: MediaStream) { const context = new AudioContext(); const analyser = context.createAnalyser(); analyser.fftSize = 128; context.createMediaStreamSource(stream).connect(analyser); audioContextRef.current = context; const values = new Uint8Array(analyser.frequencyBinCount); const draw = () => { const canvas = canvasRef.current; if (canvas) { const ctx = canvas.getContext("2d"); if (ctx) { const width = canvas.clientWidth * window.devicePixelRatio; const height = canvas.clientHeight * window.devicePixelRatio; if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; } analyser.getByteFrequencyData(values); ctx.clearRect(0, 0, width, height); const barWidth = width / values.length; values.forEach((value, index) => { const barHeight = Math.max(3, (value / 255) * height); ctx.fillStyle = "#167d69"; ctx.fillRect(index * barWidth, (height - barHeight) / 2, Math.max(2, barWidth - 2), barHeight); }); } } animationRef.current = requestAnimationFrame(draw); }; draw(); }
  function stopWaveform() { if (animationRef.current !== null) cancelAnimationFrame(animationRef.current); animationRef.current = null; void audioContextRef.current?.close(); audioContextRef.current = null; }
  async function startRecording() { stopSpeaking(); setVoiceError(null); if (!navigator.mediaDevices?.getUserMedia || !("MediaRecorder" in window)) { setVoiceError("Audio recording is unavailable in this browser. You can type the same request below."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: false, noiseSuppression: false, autoGainControl: true, channelCount: 1 } }); streamRef.current = stream; chunksRef.current = []; setRecording(true); window.setTimeout(() => startWaveform(stream), 0); const format = recordingFormat(); const recorder = new MediaRecorder(stream, format ? { mimeType: format.mimeType, audioBitsPerSecond: 128000 } : undefined); recorderRef.current = recorder; recorder.ondataavailable = (event) => { if (event.data.size) chunksRef.current.push(event.data); }; recorder.onstop = () => { const mimeType = recorder.mimeType || format?.mimeType || "audio/webm"; const extension = format?.extension || (mimeType.includes("mp4") ? "m4a" : mimeType.includes("ogg") ? "ogg" : "webm"); const blob = new Blob(chunksRef.current, { type: mimeType }); stream.getTracks().forEach((track) => track.stop()); streamRef.current = null; if (blob.size < 1000) { setVoiceError("Almost no microphone audio was captured. Check the selected Windows input device and microphone level, then try again."); return; } void sendVoice(blob, extension); }; recorder.start(); setSeconds(0); timerRef.current = window.setInterval(() => setSeconds((current) => { if (current >= 24) { stopRecording(); return 25; } return current + 1; }), 1000); } catch { setRecording(false); setVoiceError("Microphone access was not granted. Allow it in your browser or type your request."); } }
  function stopRecording() { if (timerRef.current) window.clearInterval(timerRef.current); timerRef.current = null; stopWaveform(); const recorder = recorderRef.current; if (recorder && recorder.state !== "inactive") recorder.stop(); setRecording(false); }
  async function decide(action: Proposal, decision: "confirm" | "cancel") { stopSpeaking(); setBusy(true); try { const { data } = await api.post(`/ai/actions/${action.id}/${decision}`); setMessages((m) => [...m, { role: "assistant", content: data.message }]); setMemoryMessages((m) => [...m, { role: "assistant", content: data.message }]); speak(data.message); } catch (e: any) { const message = e?.response?.data?.detail || "That action could not be completed. Nothing was changed."; setMessages((m) => [...m, { role: "assistant", content: message }]); speak(message); } finally { setBusy(false); } }

  return <Stack spacing={3} sx={{ maxWidth: 1120, mx: "auto" }}><Box><Chip label="Sarvam + OpenAI" color="success" size="small" sx={{ mb: 1 }} /><Typography variant="h3" sx={{ fontSize: { xs: "2rem", md: "2.8rem" } }}>Ask Panchayat</Typography><Typography color="text.secondary" sx={{ mt: 1, maxWidth: 760 }}>Speak in Hindi or Marathi. Sarvam translates your audio to English, then Panchayat AI safely prepares the requested action.</Typography></Box>
    <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", lg: "minmax(0,1fr) 300px" }, gap: 3 }}><Paper sx={{ overflow: "hidden", minHeight: 620, display: "flex", flexDirection: "column" }}>
      <Stack direction="row" alignItems="center" spacing={1.5} sx={{ p: 2, borderBottom: 1, borderColor: "divider" }}><Box sx={{ width: 42, height: 42, borderRadius: "50%", bgcolor: "primary.main", color: "primary.contrastText", display: "grid", placeItems: "center" }}><HearingRounded /></Box><Box sx={{ flex: 1 }}><Typography fontWeight={750}>Panchayat Assistant</Typography><Typography variant="caption" color="text.secondary">Permission checked • confirmation required</Typography></Box><TextField select SelectProps={{ native: true }} size="small" value={language} onChange={(e) => setLanguage(e.target.value)} disabled={recording || busy} inputProps={{ "aria-label": "Spoken language" }}><option value="hi-IN">हिन्दी</option><option value="mr-IN">मराठी</option><option value="en-IN">English</option></TextField></Stack>
      <Stack spacing={2} sx={{ p: { xs: 2, md: 3 }, flex: 1, overflowY: "auto", maxHeight: 520 }} aria-live="polite">{messages.map((m, i) => <Box key={i} sx={{ alignSelf: m.role === "user" ? "flex-end" : "flex-start", maxWidth: "90%" }}><Paper elevation={0} sx={{ p: 2, bgcolor: m.role === "user" ? "primary.main" : "action.hover", color: m.role === "user" ? "primary.contrastText" : "text.primary", border: 0 }}><Typography>{m.content}</Typography>{m.role === "assistant" && <IconButton size="small" aria-label={speakingText === m.content ? "Stop reading response" : "Read this response aloud"} onClick={() => speakingText === m.content ? stopSpeaking() : speak(m.content)} sx={{ mt: .5 }}>{speakingText === m.content ? <StopCircleRounded fontSize="small" /> : <VolumeUpRounded fontSize="small" />}</IconButton>}</Paper>{m.action && <ActionCard action={m.action} busy={busy} decide={decide} />}</Box>)}{busy && <Stack direction="row" spacing={1.5} alignItems="center"><CircularProgress size={20} /><Typography color="text.secondary">Processing securely…</Typography></Stack>}<div ref={endRef} /></Stack>
      <Box sx={{ p: 2, borderTop: 1, borderColor: "divider" }}>{voiceError && <Alert severity="warning" sx={{ mb: 1.5 }} onClose={() => setVoiceError(null)}>{voiceError}</Alert>}<Stack direction="row" spacing={1} alignItems="center"><IconButton aria-label={recording ? "Stop recording" : "Record Hindi or Marathi request"} onClick={recording ? stopRecording : startRecording} disabled={busy} sx={{ bgcolor: recording ? "error.main" : "primary.main", color: recording ? "error.contrastText" : "primary.contrastText", "&:hover": { bgcolor: recording ? "error.dark" : "primary.dark" } }}>{recording ? <StopCircleRounded /> : <MicRounded />}</IconButton>{recording ? <Paper variant="outlined" sx={{ flex: 1, height: 56, px: 2, display: "flex", alignItems: "center", gap: 2, overflow: "hidden" }}><canvas ref={canvasRef} role="img" aria-label="Live microphone sound level" style={{ width: "100%", height: 38 }} /><Typography color="error" fontWeight={800} sx={{ whiteSpace: "nowrap" }}>{seconds}s</Typography></Paper> : <TextField fullWidth value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void send(); } }} placeholder="Type your request" inputProps={{ "aria-label": "Message to Panchayat Assistant" }} />}<IconButton aria-label="Send message" color="primary" onClick={() => void send()} disabled={!input.trim() || busy || recording}><SendRounded /></IconButton></Stack>{recording && <Typography role="status" color="text.secondary" fontWeight={650} sx={{ mt: 1 }}>Speak now. Moving bars mean your voice is being captured. Press stop when finished.</Typography>}</Box>
    </Paper><Stack spacing={2}><Paper sx={{ p: 2.5 }}><Typography variant="h6">Try asking</Typography><Stack spacing={1} sx={{ mt: 1.5 }}>{prompts.map((prompt) => <Button key={prompt} variant="outlined" color="inherit" startIcon={<KeyboardRounded />} onClick={() => void send(prompt)} sx={{ justifyContent: "flex-start", textAlign: "left", height: "auto", py: 1.25 }}>{prompt}</Button>)}</Stack></Paper><Paper sx={{ p: 2.5 }}><TranslateRounded color="primary" /><Typography variant="h6" sx={{ mt: 1 }}>How voice works</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Your short recording is sent to Sarvam for translation. Only the English transcript is sent to OpenAI for action routing.</Typography></Paper></Stack></Box>
  </Stack>;
}

function ActionCard({ action, busy, decide }: { action: Proposal; busy: boolean; decide: (action: Proposal, decision: "confirm" | "cancel") => Promise<void> }) { return <Paper sx={{ mt: 1.5, p: 2.5, borderLeft: 5, borderColor: action.risk === "high" ? "error.main" : "secondary.main" }}><Stack direction="row" justifyContent="space-between"><Typography variant="overline" fontWeight={800}>Action to review</Typography><Chip label={`${action.risk} risk`} color={action.risk === "high" ? "error" : "warning"} size="small" /></Stack><Typography variant="h6" sx={{ mt: .5 }}>{action.summary}</Typography><Divider sx={{ my: 1.5 }} />{Object.entries(action.fields).filter(([key]) => !["society_id", "flat_id", "bill_id"].includes(key)).map(([key, value]) => <Stack key={key} direction="row" spacing={2} sx={{ py: .5 }}><Typography variant="body2" color="text.secondary" sx={{ width: 110, textTransform: "capitalize" }}>{key.replaceAll("_", " ")}</Typography><Typography variant="body2" fontWeight={650}>{typeof value === "boolean" ? (value ? "Yes" : "No") : String(value)}</Typography></Stack>)}<Alert severity="info" sx={{ mt: 1.5 }}>Nothing changes until you confirm.</Alert><Stack direction={{ xs: "column", sm: "row" }} spacing={1.5} sx={{ mt: 2 }}><Button variant="contained" startIcon={<CheckCircleRounded />} onClick={() => void decide(action, "confirm")} disabled={busy}>Confirm action</Button><Button variant="outlined" color="inherit" startIcon={<CancelOutlined />} onClick={() => void decide(action, "cancel")} disabled={busy}>Cancel</Button></Stack></Paper>; }
