import { useEffect, useRef, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, Divider, IconButton, Paper, Stack, TextField, Typography } from "@mui/material";
import { CancelOutlined, CheckCircleRounded, HearingRounded, KeyboardRounded, MicRounded, SendRounded, StopCircleRounded, TranslateRounded, VolumeUpRounded } from "@mui/icons-material";
import { api } from "../api/client";

interface Proposal { id: number; action_type: string; risk: string; status: string; summary: string; fields: Record<string, unknown>; expires_at: string }
interface Message { role: "user" | "assistant"; content: string; action?: Proposal }
const prompts = ["There has been no water near my house since morning", "Pay my maintenance fee for this month", "Show my recent complaints", "What are the latest notices?"];

export default function AI() {
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "Namaste. Speak in Hindi or Marathi, or type your request. I will check the right records and ask before making changes." }]);
  const [input, setInput] = useState(""); const [busy, setBusy] = useState(false); const [recording, setRecording] = useState(false); const [seconds, setSeconds] = useState(0);
  const [language, setLanguage] = useState("hi-IN"); const [voiceError, setVoiceError] = useState<string | null>(null);
  const endRef = useRef<HTMLDivElement>(null); const recorderRef = useRef<MediaRecorder | null>(null); const streamRef = useRef<MediaStream | null>(null); const chunksRef = useRef<Blob[]>([]); const timerRef = useRef<number | null>(null);
  useEffect(() => {
  endRef.current?.scrollIntoView({ behavior: "smooth" });
}, [messages, busy]);

useEffect(() => {
  return () => {
    streamRef.current?.getTracks().forEach((track) => {
      track.stop();
    });

    if (timerRef.current !== null) {
      window.clearInterval(timerRef.current);
    }
  };
}, []);

  function appendResult(data: any, translated?: string) { if (translated) setMessages((m) => [...m, { role: "user", content: `Translated to English: ${translated}` }, { role: "assistant", content: data.reply, action: data.action }]); else setMessages((m) => [...m, { role: "assistant", content: data.reply, action: data.action }]); }
  async function send(text = input) { if (!text.trim() || busy) return; setMessages((m) => [...m, { role: "user", content: text.trim() }]); setInput(""); setBusy(true); try { const { data } = await api.post("/ai/chat", { message: text.trim(), language }); appendResult(data); } catch (e: any) { setMessages((m) => [...m, { role: "assistant", content: e?.response?.data?.detail || "The AI service could not be reached. Manual services still work." }]); } finally { setBusy(false); } }
  async function sendVoice(blob: Blob) { setBusy(true); try { const form = new FormData(); form.append("audio", blob, "panchayat-request.webm"); form.append("language", language); const { data } = await api.post("/ai/voice", form, { timeout: 45_000 }); appendResult(data, data.input_transcript); } catch (e: any) { setVoiceError(e?.response?.data?.detail || "The recording could not be translated. Please retry or type your request."); } finally { setBusy(false); } }
  async function startRecording() { setVoiceError(null); if (!navigator.mediaDevices?.getUserMedia || !("MediaRecorder" in window)) { setVoiceError("Audio recording is unavailable in this browser. You can type the same request below."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true, channelCount: 1 } }); streamRef.current = stream; chunksRef.current = []; const recorder = new MediaRecorder(stream); recorderRef.current = recorder; recorder.ondataavailable = (event) => { if (event.data.size) chunksRef.current.push(event.data); }; recorder.onstop = () => { const blob = new Blob(chunksRef.current, { type: recorder.mimeType || "audio/webm" }); stream.getTracks().forEach((track) => track.stop()); streamRef.current = null; if (blob.size) void sendVoice(blob); }; recorder.start(500); setSeconds(0); setRecording(true); timerRef.current = window.setInterval(() => setSeconds((current) => { if (current >= 24) { stopRecording(); return 25; } return current + 1; }), 1000); } catch { setVoiceError("Microphone access was not granted. Allow it in your browser or type your request."); } }
  function stopRecording() { if (timerRef.current) window.clearInterval(timerRef.current); timerRef.current = null; const recorder = recorderRef.current; if (recorder && recorder.state !== "inactive") recorder.stop(); setRecording(false); }
  async function decide(action: Proposal, decision: "confirm" | "cancel") { setBusy(true); try { const { data } = await api.post(`/ai/actions/${action.id}/${decision}`); setMessages((m) => [...m, { role: "assistant", content: data.message }]); } catch (e: any) { setMessages((m) => [...m, { role: "assistant", content: e?.response?.data?.detail || "That action could not be completed. Nothing was changed." }]); } finally { setBusy(false); } }
  function speak(text: string) { if (!("speechSynthesis" in window)) { setVoiceError("Read aloud is unavailable in this browser."); return; } window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = language; window.speechSynthesis.speak(utterance); }

  return <Stack spacing={3} sx={{ maxWidth: 1120, mx: "auto" }}><Box><Chip label="Sarvam + OpenAI" color="success" size="small" sx={{ mb: 1 }} /><Typography variant="h3" sx={{ fontSize: { xs: "2rem", md: "2.8rem" } }}>Ask Panchayat</Typography><Typography color="text.secondary" sx={{ mt: 1, maxWidth: 760 }}>Speak in Hindi or Marathi. Sarvam translates your audio to English, then Panchayat AI safely prepares the requested action.</Typography></Box>
    <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", lg: "minmax(0,1fr) 300px" }, gap: 3 }}><Paper sx={{ overflow: "hidden", minHeight: 620, display: "flex", flexDirection: "column" }}>
      <Stack direction="row" alignItems="center" spacing={1.5} sx={{ p: 2, borderBottom: 1, borderColor: "divider" }}><Box sx={{ width: 42, height: 42, borderRadius: "50%", bgcolor: "primary.main", color: "primary.contrastText", display: "grid", placeItems: "center" }}><HearingRounded /></Box><Box sx={{ flex: 1 }}><Typography fontWeight={750}>Panchayat Assistant</Typography><Typography variant="caption" color="text.secondary">Permission checked • confirmation required</Typography></Box><TextField select SelectProps={{ native: true }} size="small" value={language} onChange={(e) => setLanguage(e.target.value)} disabled={recording || busy} inputProps={{ "aria-label": "Spoken language" }}><option value="hi-IN">हिन्दी</option><option value="mr-IN">मराठी</option><option value="en-IN">English</option></TextField></Stack>
      <Stack spacing={2} sx={{ p: { xs: 2, md: 3 }, flex: 1, overflowY: "auto", maxHeight: 520 }} aria-live="polite">{messages.map((m, i) => <Box key={i} sx={{ alignSelf: m.role === "user" ? "flex-end" : "flex-start", maxWidth: "90%" }}><Paper elevation={0} sx={{ p: 2, bgcolor: m.role === "user" ? "primary.main" : "action.hover", color: m.role === "user" ? "primary.contrastText" : "text.primary", border: 0 }}><Typography>{m.content}</Typography>{m.role === "assistant" && <IconButton size="small" aria-label="Read this response aloud" onClick={() => speak(m.content)} sx={{ mt: .5 }}><VolumeUpRounded fontSize="small" /></IconButton>}</Paper>{m.action && <ActionCard action={m.action} busy={busy} decide={decide} />}</Box>)}{busy && <Stack direction="row" spacing={1.5} alignItems="center"><CircularProgress size={20} /><Typography color="text.secondary">Processing securely…</Typography></Stack>}<div ref={endRef} /></Stack>
      <Box sx={{ p: 2, borderTop: 1, borderColor: "divider" }}>{voiceError && <Alert severity="warning" sx={{ mb: 1.5 }} onClose={() => setVoiceError(null)}>{voiceError}</Alert>}<Stack direction="row" spacing={1}><IconButton aria-label={recording ? "Stop recording" : "Record Hindi or Marathi request"} onClick={recording ? stopRecording : startRecording} disabled={busy} sx={{ bgcolor: recording ? "error.main" : "primary.main", color: recording ? "error.contrastText" : "primary.contrastText", "&:hover": { bgcolor: recording ? "error.dark" : "primary.dark" } }}>{recording ? <StopCircleRounded /> : <MicRounded />}</IconButton><TextField fullWidth value={input} onChange={(e) => setInput(e.target.value)} disabled={recording} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void send(); } }} placeholder={recording ? `Recording… ${seconds}s / 25s` : "Type your request"} inputProps={{ "aria-label": "Message to Panchayat Assistant" }} /><IconButton aria-label="Send message" color="primary" onClick={() => void send()} disabled={!input.trim() || busy || recording}><SendRounded /></IconButton></Stack>{recording && <Typography role="status" color="error" fontWeight={750} sx={{ mt: 1 }}>Recording {seconds} seconds. Press stop when finished.</Typography>}</Box>
    </Paper><Stack spacing={2}><Paper sx={{ p: 2.5 }}><Typography variant="h6">Try asking</Typography><Stack spacing={1} sx={{ mt: 1.5 }}>{prompts.map((prompt) => <Button key={prompt} variant="outlined" color="inherit" startIcon={<KeyboardRounded />} onClick={() => void send(prompt)} sx={{ justifyContent: "flex-start", textAlign: "left", height: "auto", py: 1.25 }}>{prompt}</Button>)}</Stack></Paper><Paper sx={{ p: 2.5 }}><TranslateRounded color="primary" /><Typography variant="h6" sx={{ mt: 1 }}>How voice works</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Your short recording is sent to Sarvam for translation. Only the English transcript is sent to OpenAI for action routing.</Typography></Paper></Stack></Box>
  </Stack>;
}

function ActionCard({ action, busy, decide }: { action: Proposal; busy: boolean; decide: (action: Proposal, decision: "confirm" | "cancel") => Promise<void> }) { return <Paper sx={{ mt: 1.5, p: 2.5, borderLeft: 5, borderColor: action.risk === "high" ? "error.main" : "secondary.main" }}><Stack direction="row" justifyContent="space-between"><Typography variant="overline" fontWeight={800}>Action to review</Typography><Chip label={`${action.risk} risk`} color={action.risk === "high" ? "error" : "warning"} size="small" /></Stack><Typography variant="h6" sx={{ mt: .5 }}>{action.summary}</Typography><Divider sx={{ my: 1.5 }} />{Object.entries(action.fields).filter(([key]) => !["society_id", "flat_id", "bill_id"].includes(key)).map(([key, value]) => <Stack key={key} direction="row" spacing={2} sx={{ py: .5 }}><Typography variant="body2" color="text.secondary" sx={{ width: 110, textTransform: "capitalize" }}>{key.replaceAll("_", " ")}</Typography><Typography variant="body2" fontWeight={650}>{typeof value === "boolean" ? (value ? "Yes" : "No") : String(value)}</Typography></Stack>)}<Alert severity="info" sx={{ mt: 1.5 }}>Nothing changes until you confirm.</Alert><Stack direction={{ xs: "column", sm: "row" }} spacing={1.5} sx={{ mt: 2 }}><Button variant="contained" startIcon={<CheckCircleRounded />} onClick={() => void decide(action, "confirm")} disabled={busy}>Confirm action</Button><Button variant="outlined" color="inherit" startIcon={<CancelOutlined />} onClick={() => void decide(action, "cancel")} disabled={busy}>Cancel</Button></Stack></Paper>; }
