import { useMemo, useState } from "react";
import { Alert, Avatar, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, InputAdornment, Paper, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import { AdminPanelSettingsRounded, BadgeRounded, GroupsRounded, MailOutlineRounded, ManageAccountsRounded, PersonRounded, PhoneRounded, SearchRounded, SecurityRounded, VerifiedUserRounded } from "@mui/icons-material";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { enqueueSnackbar } from "notistack";
import { api } from "../api/client";
import { LoadingPanel } from "../components/StateViews";
import { useAuthStore } from "../store/auth";
import type { User } from "../types/api";

const roleColors: Record<string, string> = { admin: "#D76049", committee: "#6D729C", security: "#2B805F", resident: "#3A6EA5" };

export default function Residents() {
  const me = useAuthStore((state) => state.user);
  const admin = Boolean(me?.is_superuser || me?.roles.some((role) => role.name === "admin"));
  const [search, setSearch] = useState("");
  const [role, setRole] = useState("all");
  const [selected, setSelected] = useState<User | null>(null);
  const users = useQuery({ queryKey: ["users"], queryFn: async () => (await api.get<User[]>("/admin/users?limit=200")).data });
  const filtered = useMemo(() => (users.data ?? []).filter((user) => {
    const roleMatch = role === "all" || user.roles.some((item) => item.name === role);
    const text = `${user.full_name} ${user.email} ${user.phone || ""}`.toLowerCase();
    return roleMatch && text.includes(search.toLowerCase());
  }), [role, search, users.data]);
  if (users.isLoading) return <LoadingPanel />;
  const count = (name: string) => (users.data ?? []).filter((user) => user.roles.some((item) => item.name === name)).length;
  return <Stack spacing={3}>
    <Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ md: "end" }} spacing={2}><Box><Typography variant="overline" color="primary" fontWeight={900} letterSpacing={1.6}>PEOPLE DIRECTORY</Typography><Typography variant="h2" sx={{ fontSize: { xs: "2.4rem", md: "3.7rem" } }}>Your community, clearly organized</Typography><Typography color="text.secondary" sx={{ mt: 1, maxWidth: 720 }}>Find a verified member and understand who can help. Only administrators can change access.</Typography></Box><Chip icon={<VerifiedUserRounded />} label={`${users.data?.length ?? 0} verified accounts`} color="success" variant="outlined" /></Stack>
    <Box sx={{ display: "grid", gridTemplateColumns: { xs: "repeat(2, 1fr)", md: "repeat(4, 1fr)" }, gap: 1.5 }}><PeopleMetric label="Residents" value={count("resident")} color={roleColors.resident} icon={<PersonRounded />} /><PeopleMetric label="Committee" value={count("committee")} color={roleColors.committee} icon={<GroupsRounded />} /><PeopleMetric label="Gate security" value={count("security")} color={roleColors.security} icon={<SecurityRounded />} /><PeopleMetric label="Administrators" value={count("admin")} color={roleColors.admin} icon={<AdminPanelSettingsRounded />} /></Box>
    <Paper sx={{ overflow: "hidden" }}><Stack direction={{ xs: "column", lg: "row" }} justifyContent="space-between" alignItems={{ lg: "center" }} spacing={1} sx={{ px: 2, pt: 1 }}><Tabs value={role} onChange={(_event, value) => setRole(value)} variant="scrollable" aria-label="Filter people by responsibility"><Tab value="all" label="Everyone" /><Tab value="resident" label="Residents" /><Tab value="committee" label="Committee" /><Tab value="security" label="Security" /><Tab value="admin" label="Admins" /></Tabs><TextField size="small" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, email, phone" InputProps={{ startAdornment: <InputAdornment position="start"><SearchRounded /></InputAdornment> }} sx={{ minWidth: { lg: 300 }, pb: { xs: 2, lg: 1 } }} /></Stack><Divider />
      <Box sx={{ p: 2, display: "grid", gridTemplateColumns: { xs: "1fr", md: "repeat(2, 1fr)", xl: "repeat(3, 1fr)" }, gap: 1.5 }}>{filtered.map((user) => <PersonCard key={user.id} user={user} canManage={admin} onManage={() => setSelected(user)} />)}</Box>
      {filtered.length === 0 && <Box sx={{ textAlign: "center", py: 8 }}><SearchRounded sx={{ fontSize: 48, color: "text.disabled" }} /><Typography variant="h6">No people match this view</Typography><Typography color="text.secondary">Change the role filter or search words.</Typography></Box>}
    </Paper><RoleDialog user={selected} onClose={() => setSelected(null)} />
  </Stack>;
}

function PersonCard({ user, canManage, onManage }: { user: User; canManage: boolean; onManage: () => void }) {
  const initials = user.full_name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
  return <Paper variant="outlined" sx={{ p: 2.25, display: "flex", flexDirection: "column", minHeight: 230, bgcolor: "background.default" }}><Stack direction="row" justifyContent="space-between" alignItems="start"><Avatar sx={{ width: 56, height: 56, bgcolor: roleColors[user.roles[0]?.name] || "primary.main", fontWeight: 900 }}>{initials}</Avatar><Chip size="small" icon={<BadgeRounded />} label={user.status} color={user.status === "active" ? "success" : "default"} variant="outlined" /></Stack><Typography variant="h6" sx={{ mt: 2 }}>{user.full_name}</Typography><Stack spacing={.5} sx={{ mt: .75 }}><Stack direction="row" spacing={1} alignItems="center"><MailOutlineRounded fontSize="small" color="disabled" /><Typography variant="body2" color="text.secondary" noWrap>{user.email}</Typography></Stack><Stack direction="row" spacing={1} alignItems="center"><PhoneRounded fontSize="small" color="disabled" /><Typography variant="body2" color="text.secondary">{user.phone || "No phone listed"}</Typography></Stack></Stack><Stack direction="row" spacing={.75} flexWrap="wrap" useFlexGap sx={{ mt: 2 }}>{user.roles.map((item) => <Chip key={item.id} size="small" label={item.name} sx={{ bgcolor: `${roleColors[item.name] || "#68736E"}18`, color: roleColors[item.name] || "text.primary", fontWeight: 800 }} />)}</Stack>{canManage && <Button startIcon={<ManageAccountsRounded />} onClick={onManage} sx={{ mt: "auto", alignSelf: "flex-start" }}>Manage access</Button>}</Paper>;
}

function RoleDialog({ user, onClose }: { user: User | null; onClose: () => void }) {
  const qc = useQueryClient();
  const [permanentAdmin, setPermanentAdmin] = useState(false);
  const mutation = useMutation({ mutationFn: async ({ role, add }: { role: string; add: boolean }) => add ? api.post(`/admin/users/${user!.id}/roles/${role}`) : api.delete(`/admin/users/${user!.id}/roles/${role}`), onSuccess: async () => { enqueueSnackbar("Access updated", { variant: "success" }); setPermanentAdmin(false); await qc.invalidateQueries({ queryKey: ["users"] }); onClose(); }, onError: (error: any) => enqueueSnackbar(error?.response?.data?.detail || "Access could not be changed", { variant: "error" }) });
  if (!user) return null;
  const has = (name: string) => user.roles.some((item) => item.name === name);
  return <Dialog open onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Access for {user.full_name}</DialogTitle><DialogContent><Alert severity="info" sx={{ mb: 2 }}>Role changes take effect the next time this person signs in. Passwords and private credentials are never shown here.</Alert><Stack spacing={1.25}><RoleRow icon={<AdminPanelSettingsRounded />} title="Administrator" detail="Full control. This role cannot be removed in the app." active={has("admin")} permanent onAdd={() => setPermanentAdmin(true)} /><RoleRow icon={<GroupsRounded />} title="Committee" detail="Complaints, notices, bills, and community records." active={has("committee")} onAdd={() => mutation.mutate({ role: "committee", add: true })} onRemove={() => mutation.mutate({ role: "committee", add: false })} /><RoleRow icon={<SecurityRounded />} title="Gate security" detail="Approved visitor entry and exit operations." active={has("security")} onAdd={() => mutation.mutate({ role: "security", add: true })} onRemove={() => mutation.mutate({ role: "security", add: false })} /><RoleRow icon={<PersonRounded />} title="Resident" detail="Personal dues, complaints, visitors, and notices." active={has("resident")} onAdd={() => mutation.mutate({ role: "resident", add: true })} onRemove={() => mutation.mutate({ role: "resident", add: false })} /></Stack>{permanentAdmin && <Alert severity="warning" sx={{ mt: 2 }}><Typography fontWeight={850}>Permanent administrator access</Typography><Typography variant="body2">This cannot be undone from the application. Grant it only to a trusted society administrator.</Typography><Stack direction="row" spacing={1} sx={{ mt: 1.5 }}><Button onClick={() => setPermanentAdmin(false)}>Cancel</Button><Button variant="contained" color="warning" onClick={() => mutation.mutate({ role: "admin", add: true })}>Grant admin access</Button></Stack></Alert>}</DialogContent><DialogActions><Button onClick={onClose}>Done</Button></DialogActions></Dialog>;
}

function RoleRow({ icon, title, detail, active, permanent, onAdd, onRemove }: { icon: React.ReactNode; title: string; detail: string; active: boolean; permanent?: boolean; onAdd: () => void; onRemove?: () => void }) { return <Paper variant="outlined" sx={{ p: 2 }}><Stack direction="row" spacing={1.5} alignItems="center"><Box sx={{ width: 44, height: 44, borderRadius: 2, bgcolor: active ? "primary.main" : "action.hover", color: active ? "primary.contrastText" : "text.secondary", display: "grid", placeItems: "center" }}>{icon}</Box><Box sx={{ flex: 1 }}><Typography fontWeight={850}>{title}</Typography><Typography variant="body2" color="text.secondary">{detail}</Typography></Box>{active ? permanent ? <Chip size="small" label="Permanent" /> : <Button size="small" color="error" onClick={onRemove}>Remove</Button> : <Button size="small" variant="outlined" onClick={onAdd}>Add role</Button>}</Stack></Paper>; }
function PeopleMetric({ label, value, color, icon }: { label: string; value: number; color: string; icon: React.ReactNode }) { return <Paper sx={{ p: 2, borderLeft: `4px solid ${color}` }}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h4">{value}</Typography><Typography variant="body2" color="text.secondary">{label}</Typography></Box><Box sx={{ color }}>{icon}</Box></Stack></Paper>; }
